Repository fusionjs/fusion-plugin-i18n-react, pull requests merged in 2018-11, with the labels that each got.

#184 Support leveraging React.Fragment when applicable
  .buildkite/nodeTests
  app-fixture/.fusionrc.js
  app-fixture/.gitignore
  app-fixture/src/main.js
  app-fixture/src/root.js
  package.json
  src/__tests__/index.node.js
  src/__tests__/integration/integration.node.js
  src/translate.js
  yarn.lock
Labels: feature

#186 Release v1.2.0
  package.json
Labels: release

#185 Update flow types for 0.85
  package.json
  src/__tests__/integration/integration.node.js
  src/plugin.js
  yarn.lock
Labels: bugfix, dependencies, greenkeeping

#187 Release v1.2.1-0
  package.json
Labels: release

#189 Upgrade deps
  package.json
  yarn.lock
Labels: greenkeeping

#190 Release v1.2.1
  package.json
Labels: release

#193 Upgrade dependencies
  package.json
  yarn.lock
Labels: greenkeeping
