Repository fusionjs/fusion-plugin-i18n-react, pull requests merged in 2018-12, with the labels that each got.

#192 Include types for 'locale' module from fusion-plugin-i18n
  .flowconfig
  package.json
  yarn.lock
Labels: bugfix

#196 Fix tests for release verification
  package.json
  src/__tests__/integration/integration.node.js
  src/with-translations.js
  yarn.lock
Labels: bugfix, greenkeeping

#200 Upgrade dependencies to @latest
  package.json
  yarn.lock
Labels: greenkeeping
