Repository fusionjs/fusion-plugin-i18n-react, pull requests merged in 2018-10, with the labels that each got.

#170 Upgrade dependency versions
  package.json
  yarn.lock
Labels: greenkeeping

#177 Upgrade dependencies to @latest
  package.json
  yarn.lock
Labels: bugfix, dependencies

#178 Release v1.1.1-0
  package.json
Labels: prerelease, release

#175 Improve typing for withTranslations HOC
  src/index.js
  src/with-translations.js
Labels: bugfix

#182 Release v1.1.1-1
  package.json
Labels: release

#180 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor

#183 Release v1.1.1
  package.json
Labels: release
