Repository fusionjs/fusion-plugin-i18n-react, pull requests merged in 2019-01, with the labels that each got.

#212 Update README to fix withDependencies naming
  README.md
Labels: docs

#216 Release v1.2.2-1
  package.json
Labels: release

#221 Update fusion-plugin-i18n to 1.2.0
  package.json
  yarn.lock
Labels: greenkeeping

#223 Upgrade fusion-react to 1.3.7
  package.json
  yarn.lock
Labels: greenkeeping

#222 Release v1.2.3
  package.json
Labels: release
