Repository fusionjs/fusion-plugin-i18n-react, pull requests merged in 2019-04, with the labels that each got.

#233 Export passed through types for TranslationsObjectType and TranslateFuncType
  package.json
  src/index.js
  yarn.lock
Labels: bugfix

#235 Release v1.2.5
  package.json
Labels: release

#236 Upgrade i18n plugin
  package.json
  yarn.lock
Labels: bugfix

#237 Release v1.2.6
  package.json
Labels: release

#238 Feature: pass localeCode along with the translate prop in the withTra…
  README.md
  package.json
  src/__tests__/__snapshots__/with-translations.test.browser.js.snap
  src/__tests__/with-translations.test.browser.js
  src/setupTests.js
  src/with-translations.js
  yarn.lock
Labels: feature

#240 Use latest pre-release for fusion-plugin-i18n
  package.json
  yarn.lock
Labels: bugfix
